name: Docs

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Clean install dependencies
        run: npm ci --ignore-scripts

      - name: Build
        run: |
          npm run build

      - name: Build Storybook
        run: |
          npm run build-storybook

      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: storybook-static
          clean: true
